### ISSUE TITLE
Add LinkedIn Identity

### ISSUE THREAD

**Issue by elagerway** [openpeer/opios#194] opened 2014-02-18 20:27 UTC
Please add LinkedIn login

1. Rolodex work
2. Client JS - LinkedIn Button

Please re-assign as appropriate. Maybe Marko can do this work ?

**Comment by cadorn** [comment] 2015-02-24 21:32
Duplicate of: https://github.com/openpeer/hcs-server-rolodex-nodejs/issues/6

**Closed by cadorn** 2015-02-24 21:32 UTC
Labels: enhancement, FEATURE, ISOLATED
